# Site settings
title: TUREUS
email: xrlange@tureus.com
description: >
  TURUES is a full stack software consultancy based in San Diego, CA.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: tureus
github_username:  xrl

# Build settings
markdown: kramdown
